services:
    spenderella:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mailpit
            - mariadb

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

    mariadb:
        image: mariadb:lts
        volumes:
            - mariadb-data:/var/lib/mysql:Z
        environment:
            MARIADB_ROOT_PASSWORD: spenderella
        ports:
            - '3306:3306'
        networks:
            - sail

    adminer:
        image: shyim/adminerevo:latest
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
            ADMINER_DEFAULT_USER: spenderella
            ADMINER_DEFAULT_PASSWORD: spenderella
            ADMINER_DEFAULT_DB: spenderella
        ports:
            - '8081:8080'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    mariadb-data:
