services:
    spenderella:
        build:
            context: .
            dockerfile: Dockerfile
        image: spenderella
        ports:
            - '8080:80'
        volumes:
            - ../:/var/www
            - ./storage:/var/www/storage
            - ./database.sqlite:/var/www/database/database.sqlite
        networks:
            - spenderella

networks:
    spenderella:
        driver: bridge
